# Use a imagem base do Python
FROM python:3.9-slim

# Defina o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copie o arquivo do Broker para o diretório de trabalho
COPY broker.py .

# Instale o Flask
RUN pip install flask

# Exponha a porta do serviço do Broker
EXPOSE 5555

# Comando para iniciar o Broker
CMD ["python", "broker.py"]