# Use a imagem base do Python
FROM python:3.9-slim

# Defina o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copie os arquivos banco_a.py e banco.py para o diretório de trabalho no contêiner
COPY banco_a.py banco_a.py
COPY banco.py banco.py
COPY contaFisica.py contaFisica.py
COPY contaPJ.py  contaPJ.py 
COPY contaConjunta.py contaConjunta.py
COPY contaBancaria.py contaBancaria.py
# Instale as dependências necessárias (Flask e requests)
RUN pip install flask requests

# Comando para iniciar o script banco_a.py
CMD ["python", "banco_a.py"]